# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: build, lint and test
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build
          npm run build-examples
          npm run build-doc
      - name: Commit to public
        uses: EndBug/add-and-commit@v7
        with:
          add: 'build build-examples doc --force'
          message: 'Update Examples and Doc'
          push: 'origin HEAD:public --force'